### ISSUE TITLE
issue running on debian

### ISSUE THREAD

**Issue by killmasta93** [sulaweyo/r710-fan-control#1]
Hi,
I was wanting to give a try on your script,
But after installing 
`apt-get install gem`
then i tried installing the bundler but i get this error
Not much familiar on installing ruby 

```
 gem install bundler
-bash: gem: command not found

```

Thank you

**Comment by killmasta93** [comment]
edit: 
the steps
```

apt install ruby-full
gem install thor
gem install colorize
```
but im trying to copy the service which i changed the user and group to root but i keep get this issue

```
● fan-control.service - R710 fan control
   Loaded: loaded (/etc/systemd/system/fan-control.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Jul 26 15:39:07 prometheus systemd[1]: /etc/systemd/system/fan-control.service:5: Invalid user/group name or numeric ID: <your user>
```

**Comment by sulaweyo** [comment]
From the message in the log i'd say you did not save your changes or did not reload systemd 'systemd daemon-reload' as it says it does not find the user id <your user> which is the default placeholder.

Please be careful with the config values - while the fan control will try to shut itself off if the CPU get's too hot there are other components that might build up heat on low fan rates. Disks and PSU come to mind - disks have longer lifetime if they run cooler and the PSU will ramp up it's own fan if it gets too hot. So be sure to have proper monitoring in place

**Comment by killmasta93** [comment]
thanks for the reply, will keep that in mind i had to move the folder to opt thanks everything is working flawless
